api_login_check:
  path: /api/login_check

comment:
  type     : rest
  resource : App\Controller\CommentController
  prefix   : /api/

movie:
  type     : rest
  resource : App\Controller\MovieController
  prefix   : /api/

user:
  type     : rest
  resource : App\Controller\UserController
  prefix   : /api/
